### PR TITLE
fix: allow esbuild 0.13.x & bump other deps

### PR DESCRIPTION
**Pull request by Dev-CasperTheGhost**
**What**:

Allow installing this package when using esbuild@0.13

**Why**:

fixes an npm error that occurs when using esbuild@0.13 

**How**:

- bump dependencies

**Checklist**:

- [ ] Documentation
- [x] Tests
- [x] Ready to be merged

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Thanks!

**Comment by kentcdodds** [comment]
@All-contributors please add @Dev-CasperTheGhost for code

**Comment by shivamjjha** [comment]
esbuild 0.16.7 is out now: https://github.com/evanw/esbuild/releases/tag/v0.16.7
But seems the latest`mdx-bundler` allows is `0.14.x`

Giving error:

```shell
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: mdx-bundler@9.0.1
npm ERR! Found: esbuild@0.16.7
npm ERR! node_modules/esbuild
npm ERR!   esbuild@"^0.16.7" from the root project
npm ERR!   peer esbuild@"*" from @esbuild-plugins/node-resolve@0.1.4
npm ERR!   node_modules/@esbuild-plugins/node-resolve
npm ERR!     @esbuild-plugins/node-resolve@"^0.1.4" from mdx-bundler@9.0.1
npm ERR!     node_modules/mdx-bundler
npm ERR!       mdx-bundler@"^9.0.1" from the root project
npm ERR!   1 more (@mdx-js/esbuild)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer esbuild@"0.11.x || 0.12.x || 0.13.x || 0.14.x" from mdx-bundler@9.0.1
npm ERR! node_modules/mdx-bundler
npm ERR!   mdx-bundler@"^9.0.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: esbuild@0.14.54
npm ERR! node_modules/esbuild
npm ERR!   peer esbuild@"0.11.x || 0.12.x || 0.13.x || 0.14.x" from mdx-bundler@9.0.1
npm ERR!   node_modules/mdx-bundler
npm ERR!     mdx-bundler@"^9.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

**Comment by kentcdodds** [comment]
This has been resolved

**Comment by shivamjjha** [comment]
Thanks a bunch!

**Pull request merged**
