### PR TITLE
Replace xdm with MDX v2

### LINKED ISSUE #137: Migrate to MDX v2
Not sure where to ask questions - what is the roadmap or plans for MDX v2?  Cheers!

### PR DESCRIPTION
**Pull request by silvenon**
**What**: xdm is being replaced with MDX v2. The breaking change is that `xdmOptions` has been renamed to `mdxOptions`.

**Why**: xdm was created before MDX v2 as a project that contains everything that Titus, the core maintainer of MDX, wanted to have in MDX. With the release of MDX v2 the projects are now ["99.99% the same"](https://twitter.com/wooorm/status/1490031074520535041), and Titus will retire xdm.

**How**: it was enough to replace xdm with `@mdx-js/esbuild`, it even exports the `ProcessorOptions` needed in `types.d.ts`, so there was no need to install `@mdx-js/mdx` as well. The documentation was updated in the way that made sense to me. The only uncomfortable change is renaming `xdmOptions` to `mdxOptions`, but I believe it's necessary.

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Ready to be merged
      

Resolves #137, #159.

### CODE REVIEW

**Comment by marcofranssen** [comment]
Resolves #159 

When can we expect a release of this Fix/Version bump?

**Comment by silvenon** [comment]
> (…) but I would be willing to look at a PR for it
>
> —https://github.com/kentcdodds/mdx-bundler/issues/137#issuecomment-1030677591

I think Kent instantly regretted saying this 🤣  😜

**Comment by Arcath** [comment]
Running this branch locally and the tests are hanging on coverage, do you get the same thing?

**Comment by Arcath** [comment]
I'd also suggest that we implement the relatively minor #167 in this PR as well so its a single breaking change release.

@silvenon I have an uncomitted version of this PR with those changes made if that works for you? Same question to @kentcdodds

**Comment by silvenon** [comment]
> Running this branch locally and the tests are hanging on coverage, do you get the same thing?

I did not run the tests, I wanted to defer to the CI 😅 It's indeed hanging on the coverage part for me too, but I'm experiencing the same problem on `main` 🤔 

> I have an uncomitted version of this PR with those changes made if that works for you?

Absolutely!

**Comment by kentcdodds** [comment]
Looks like we're good to roll here! Will merge this as a breaking change. Thanks so much!

**Review by kentcdodds — APPROVED** [review]
LGTM! 👏👏

**Comment by silvenon** [comment]
Awesome! Many thanks for reviewing this ❤️

**Pull request merged**
