### PR TITLE
feat: support vfile input

### PR DESCRIPTION
**Pull request by stefanprobst**
**What**: support providing input `source` as `Vfile` with full `path`, which can be accessed by plugins on `vfile.path`

**Why**: being able to pass input to a `unified` pipeline as `VFile` is expected to work in the ecosystem i think. also, providing `remark`/`rehype` plugins with an actual source file path can be useful.

**How**: see below

**Checklist**:

- [ ] Documentation
- [x] Tests
- [x] Ready to be merged

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Cool! Thank you 👍

**Comment by kentcdodds** [comment]
If you can fix the tests then we can get this merged. Thanks.

**Comment by stefanprobst** [comment]
do you mean the type error? - i think this is unrelated - current `main` has the same error in the logs

**Comment by kentcdodds** [comment]
@All-contributors please add @stefanprobst for code and tests

**Pull request merged**
