### PR TITLE
chore: add tests for Node 16

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
https://nodejs.medium.com/node-js-16-available-now-7f5099a97e70

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Super 👍 Thanks :)

**Comment by Arcath** [comment]
Looks like the node 16 build is getting stuck at downloading deps, over an hour now on the PR workflow.

**Comment by kentcdodds** [comment]
Ooops 😅

Let's hope it just goes away, but if we need to do a release of anything and it's still a problem we'll revert and wait until it works itself out.

**Comment by MichaelDeBoey** [comment]
Looks like this is temporary, as no problem with this on other repos

**Comment by kentcdodds** [comment]
This repo is unique because it's using some different tools (due to native ESM), so I'm unsurprised this one's the trouble child 😅

I'm betting it'll just resolve itself eventually though. I personally don't have time to chase this down I'm afraid.

**Pull request merged**
